downloadButton.addEventListener('click', async () => {
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF('p', 'pt', 'letter');

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  let y = 50; // Starting y-position

  pdf.setFont('Helvetica');

  // Title - Centered
  pdf.setFontSize(20);
  pdf.setTextColor(0, 0, 0); // Black
  pdf.text('Product Dev Chat', pageWidth / 2, y, { align: 'center' });
  y += 30;

  // Subtitle - Centered
  pdf.setFontSize(12);
  pdf.setTextColor(80, 80, 80); // Dark gray
  pdf.text('Generated by the Product Coach at JoshAdams.io/product-coach', pageWidth / 2, y, { align: 'center' });
  y += 18;

  // Timestamp - Centered
  const now = new Date();
  const timestamp = now.toLocaleString('en-US', { 
    dateStyle: 'medium', 
    timeStyle: 'short' 
  });
  pdf.setFontSize(10);
  pdf.text(`Downloaded: ${timestamp}`, pageWidth / 2, y, { align: 'center' });
  y += 30;

  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0); // Back to black for chat content

  const messages = document.querySelectorAll('#chat-log > div');

  messages.forEach((wrapper, index) => {
    const name = wrapper.querySelector('strong')?.textContent || '';
    const content = wrapper.querySelector('span')?.textContent || '';

    if (y > pageHeight - 80) {
      addPageNumber(pdf);
      pdf.addPage();
      y = 50;
    }

    pdf.setFont(undefined, 'bold');
    pdf.text(name, 50, y);
    y += 16;

    pdf.setFont(undefined, 'normal');
    const lines = pdf.splitTextToSize(content, 500);
    pdf.text(lines, 60, y);
    y += lines.length * 14 + 10;
  });

  addPageNumber(pdf); // Add page number to the last page
  pdf.save('Product-Dev-Chat.pdf');

  // Helper: Add footer page numbers
  function addPageNumber(doc) {
    const pageCount = doc.internal.getNumberOfPages();
    const pageCurrent = doc.internal.getCurrentPageInfo().pageNumber;

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100); // Darker gray for page numbers
    doc.text(`Page ${pageCurrent} of ${pageCount}`, pageWidth / 2, pageHeight - 30, { align: 'center' });
    doc.setTextColor(0, 0, 0); // Reset back to black after
  }
});
